server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: nestjs-api
    static_configs:
      - targets: ["localhost:3000"]
        labels:
          job: nestjs
